// Code generated by stanc v2.38.0
#include <stan/model/model_header.hpp>
namespace herring_metapop_v1_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 99> locations_array__ =
  {" (found before start of program)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 78, column 2 to column 9)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 79, column 2 to column 15)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 82, column 2 to column 22)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 83, column 2 to column 26)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 86, column 2 to column 18)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 89, column 2 to column 27)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 92, column 2 to column 41)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 95, column 2 to column 25)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 100, column 2 to column 38)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 101, column 2 to column 29)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 102, column 2 to column 29)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 103, column 2 to column 34)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 211, column 2 to column 36)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 214, column 2 to column 33)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 106, column 2 to column 27)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 110, column 2 to column 45)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 114, column 4 to column 47)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 113, column 23 to line 115, column 3)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 113, column 2 to line 115, column 3)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 119, column 4 to column 24)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 120, column 4 to column 44)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 118, column 23 to line 121, column 3)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 118, column 2 to line 121, column 3)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 127, column 6 to column 85)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 129, column 6 to column 46)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 125, column 25 to line 130, column 5)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 125, column 4 to line 130, column 5)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 124, column 23 to line 131, column 3)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 124, column 2 to line 131, column 3)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 217, column 4 to column 16)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 220, column 8 to column 17)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 225, column 10 to column 29)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 226, column 10 to column 28)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 224, column 15 to line 227, column 9)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 222, column 10 to column 85)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 223, column 10 to column 73)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 221, column 30 to line 224, column 9)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 221, column 8 to line 227, column 9)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 219, column 27 to line 228, column 7)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 219, column 6 to line 228, column 7)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 218, column 25 to line 229, column 5)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 218, column 4 to line 229, column 5)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 216, column 2 to line 230, column 3)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 140, column 2 to column 19)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 143, column 2 to column 25)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 148, column 2 to column 31)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 151, column 2 to column 35)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 156, column 2 to column 23)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 161, column 2 to column 35)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 165, column 2 to column 25)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 168, column 2 to column 38)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 183, column 10 to column 65)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 182, column 30 to line 184, column 9)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 182, column 8 to line 184, column 9)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 181, column 27 to line 185, column 7)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 181, column 6 to line 185, column 7)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 180, column 25 to line 186, column 5)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 180, column 4 to line 186, column 5)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 194, column 6 to column 101)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 189, column 25 to line 195, column 5)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 189, column 4 to line 195, column 5)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 174, column 23 to line 196, column 3)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 174, column 2 to line 196, column 3)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 53, column 2 to column 23)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 54, column 2 to column 23)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 55, column 9 to column 16)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 55, column 18 to column 25)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 55, column 2 to column 29)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 56, column 8 to column 15)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 56, column 17 to column 24)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 56, column 2 to column 54)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 58, column 9 to column 16)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 58, column 2 to column 22)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 59, column 8 to column 15)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 59, column 2 to column 45)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 62, column 2 to column 23)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 63, column 8 to column 15)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 63, column 2 to column 55)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 64, column 8 to column 15)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 64, column 2 to column 55)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 65, column 9 to column 16)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 65, column 2 to column 28)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 68, column 2 to column 35)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 73, column 2 to column 26)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 89, column 9 to column 16)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 92, column 9 to column 20)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 92, column 22 to column 29)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 95, column 9 to column 16)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 100, column 26 to column 33)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 101, column 9 to column 16)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 101, column 18 to column 25)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 102, column 9 to column 16)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 102, column 18 to column 25)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 103, column 9 to column 16)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 103, column 18 to column 25)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 211, column 9 to column 26)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 214, column 9 to column 16)",
  " (in '/Users/adrianstier/stier-2027-herring-metapopulation/inst/stan/herring_metapop_v1.stan', line 214, column 18 to column 25)"};
class herring_metapop_v1_model final : public model_base_crtp<herring_metapop_v1_model> {
 private:
  int N_years;
  int N_sites;
  Eigen::Matrix<double,-1,-1> Y_data__;
  std::vector<std::vector<int>> Y_obs;
  Eigen::Matrix<double,-1,1> pdo_data__;
  std::vector<int> q_idx;
  int N_catch;
  std::vector<int> catch_row;
  std::vector<int> catch_col;
  Eigen::Matrix<double,-1,1> log_catch_data__;
  int prior_only;
  double sigma_catch;
  int delta_raw_1dim__;
  int log_lik_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> pdo{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> log_catch{nullptr, 0};
 public:
  ~herring_metapop_v1_model() {}
  herring_metapop_v1_model(stan::io::var_context& context__, unsigned int
                           random_seed__ = 0, std::ostream*
                           pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "herring_metapop_v1_model_namespace::herring_metapop_v1_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 64;
      context__.validate_dims("data initialization", "N_years", "int",
        std::vector<size_t>{});
      N_years = std::numeric_limits<int>::min();
      current_statement__ = 64;
      N_years = context__.vals_i("N_years")[(1 - 1)];
      current_statement__ = 64;
      stan::math::check_greater_or_equal(function__, "N_years", N_years, 1);
      current_statement__ = 65;
      context__.validate_dims("data initialization", "N_sites", "int",
        std::vector<size_t>{});
      N_sites = std::numeric_limits<int>::min();
      current_statement__ = 65;
      N_sites = context__.vals_i("N_sites")[(1 - 1)];
      current_statement__ = 65;
      stan::math::check_greater_or_equal(function__, "N_sites", N_sites, 1);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("Y", "N_years", N_years);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("Y", "N_sites", N_sites);
      current_statement__ = 68;
      context__.validate_dims("data initialization", "Y", "double",
        std::vector<size_t>{static_cast<size_t>(N_years),
          static_cast<size_t>(N_sites)});
      Y_data__ = Eigen::Matrix<double,-1,-1>::Constant(N_years, N_sites,
                   std::numeric_limits<double>::quiet_NaN());
      new (&Y) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_data__.data(),
        N_years, N_sites);
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 68;
        Y_flat__ = context__.vals_r("Y");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N_years; ++sym2__) {
            stan::model::assign(Y, Y_flat__[(pos__ - 1)],
              "assigning variable Y", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 69;
      stan::math::validate_non_negative_index("Y_obs", "N_years", N_years);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("Y_obs", "N_sites", N_sites);
      current_statement__ = 71;
      context__.validate_dims("data initialization", "Y_obs", "int",
        std::vector<size_t>{static_cast<size_t>(N_years),
          static_cast<size_t>(N_sites)});
      Y_obs = std::vector<std::vector<int>>(N_years,
                std::vector<int>(N_sites, std::numeric_limits<int>::min()));
      {
        std::vector<int> Y_obs_flat__;
        current_statement__ = 71;
        Y_obs_flat__ = context__.vals_i("Y_obs");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N_years; ++sym2__) {
            stan::model::assign(Y_obs, Y_obs_flat__[(pos__ - 1)],
              "assigning variable Y_obs", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 71;
      stan::math::check_greater_or_equal(function__, "Y_obs", Y_obs, 0);
      current_statement__ = 71;
      stan::math::check_less_or_equal(function__, "Y_obs", Y_obs, 1);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("pdo", "N_years", N_years);
      current_statement__ = 73;
      context__.validate_dims("data initialization", "pdo", "double",
        std::vector<size_t>{static_cast<size_t>(N_years)});
      pdo_data__ = Eigen::Matrix<double,-1,1>::Constant(N_years,
                     std::numeric_limits<double>::quiet_NaN());
      new (&pdo) Eigen::Map<Eigen::Matrix<double,-1,1>>(pdo_data__.data(),
        N_years);
      {
        std::vector<local_scalar_t__> pdo_flat__;
        current_statement__ = 73;
        pdo_flat__ = context__.vals_r("pdo");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
          stan::model::assign(pdo, pdo_flat__[(pos__ - 1)],
            "assigning variable pdo", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 74;
      stan::math::validate_non_negative_index("q_idx", "N_years", N_years);
      current_statement__ = 75;
      context__.validate_dims("data initialization", "q_idx", "int",
        std::vector<size_t>{static_cast<size_t>(N_years)});
      q_idx = std::vector<int>(N_years, std::numeric_limits<int>::min());
      current_statement__ = 75;
      q_idx = context__.vals_i("q_idx");
      current_statement__ = 75;
      stan::math::check_greater_or_equal(function__, "q_idx", q_idx, 1);
      current_statement__ = 75;
      stan::math::check_less_or_equal(function__, "q_idx", q_idx, 2);
      current_statement__ = 76;
      context__.validate_dims("data initialization", "N_catch", "int",
        std::vector<size_t>{});
      N_catch = std::numeric_limits<int>::min();
      current_statement__ = 76;
      N_catch = context__.vals_i("N_catch")[(1 - 1)];
      current_statement__ = 76;
      stan::math::check_greater_or_equal(function__, "N_catch", N_catch, 0);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("catch_row", "N_catch", N_catch);
      current_statement__ = 78;
      context__.validate_dims("data initialization", "catch_row", "int",
        std::vector<size_t>{static_cast<size_t>(N_catch)});
      catch_row = std::vector<int>(N_catch, std::numeric_limits<int>::min());
      current_statement__ = 78;
      catch_row = context__.vals_i("catch_row");
      current_statement__ = 78;
      stan::math::check_greater_or_equal(function__, "catch_row", catch_row,
        1);
      current_statement__ = 78;
      stan::math::check_less_or_equal(function__, "catch_row", catch_row,
        N_years);
      current_statement__ = 79;
      stan::math::validate_non_negative_index("catch_col", "N_catch", N_catch);
      current_statement__ = 80;
      context__.validate_dims("data initialization", "catch_col", "int",
        std::vector<size_t>{static_cast<size_t>(N_catch)});
      catch_col = std::vector<int>(N_catch, std::numeric_limits<int>::min());
      current_statement__ = 80;
      catch_col = context__.vals_i("catch_col");
      current_statement__ = 80;
      stan::math::check_greater_or_equal(function__, "catch_col", catch_col,
        1);
      current_statement__ = 80;
      stan::math::check_less_or_equal(function__, "catch_col", catch_col,
        N_sites);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("log_catch", "N_catch", N_catch);
      current_statement__ = 82;
      context__.validate_dims("data initialization", "log_catch", "double",
        std::vector<size_t>{static_cast<size_t>(N_catch)});
      log_catch_data__ = Eigen::Matrix<double,-1,1>::Constant(N_catch,
                           std::numeric_limits<double>::quiet_NaN());
      new (&log_catch)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(log_catch_data__.data(),
        N_catch);
      {
        std::vector<local_scalar_t__> log_catch_flat__;
        current_statement__ = 82;
        log_catch_flat__ = context__.vals_r("log_catch");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_catch; ++sym1__) {
          stan::model::assign(log_catch, log_catch_flat__[(pos__ - 1)],
            "assigning variable log_catch", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 83;
      context__.validate_dims("data initialization", "prior_only", "int",
        std::vector<size_t>{});
      prior_only = std::numeric_limits<int>::min();
      current_statement__ = 83;
      prior_only = context__.vals_i("prior_only")[(1 - 1)];
      current_statement__ = 83;
      stan::math::check_greater_or_equal(function__, "prior_only",
        prior_only, 0);
      current_statement__ = 83;
      stan::math::check_less_or_equal(function__, "prior_only", prior_only, 1);
      current_statement__ = 84;
      sigma_catch = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 84;
      sigma_catch = 0.01;
      current_statement__ = 85;
      stan::math::validate_non_negative_index("Pc_logit", "N_catch", N_catch);
      current_statement__ = 86;
      delta_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 86;
      delta_raw_1dim__ = (N_years - 1);
      current_statement__ = 86;
      stan::math::validate_non_negative_index("delta_raw", "N_years - 1",
        delta_raw_1dim__);
      current_statement__ = 87;
      stan::math::validate_non_negative_index("delta_raw", "N_sites", N_sites);
      current_statement__ = 88;
      stan::math::validate_non_negative_index("Z_init", "N_sites", N_sites);
      current_statement__ = 89;
      stan::math::validate_non_negative_index("Pc", "N_catch", N_catch);
      current_statement__ = 90;
      stan::math::validate_non_negative_index("Z", "N_years", N_years);
      current_statement__ = 91;
      stan::math::validate_non_negative_index("Z", "N_sites", N_sites);
      current_statement__ = 92;
      stan::math::validate_non_negative_index("X", "N_years", N_years);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("X", "N_sites", N_sites);
      current_statement__ = 94;
      stan::math::validate_non_negative_index("Pc_mat", "N_years", N_years);
      current_statement__ = 95;
      stan::math::validate_non_negative_index("Pc_mat", "N_sites", N_sites);
      current_statement__ = 96;
      log_lik_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 96;
      log_lik_1dim__ = (N_years * N_sites);
      current_statement__ = 96;
      stan::math::validate_non_negative_index("log_lik", "N_years * N_sites",
        log_lik_1dim__);
      current_statement__ = 97;
      stan::math::validate_non_negative_index("Y_rep", "N_years", N_years);
      current_statement__ = 98;
      stan::math::validate_non_negative_index("Y_rep", "N_sites", N_sites);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 2 + N_catch + (delta_raw_1dim__ *
      N_sites) + N_sites;
  }
  inline std::string model_name() const final {
    return "herring_metapop_v1_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.38.0",
             "stancflags = --warn-pedantic"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "herring_metapop_v1_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto U = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto pdocoef = in__.template read<local_scalar_t__>();
      current_statement__ = 3;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 4;
      auto sigma_obs =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 5;
      auto log_q =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(2);
      current_statement__ = 6;
      auto Pc_logit =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_catch);
      current_statement__ = 7;
      auto delta_raw =
        in__.template read<
          Eigen::Matrix<local_scalar_t__,-1,-1>>(delta_raw_1dim__, N_sites);
      current_statement__ = 8;
      auto Z_init =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_sites);
      Eigen::Matrix<local_scalar_t__,-1,1> Pc =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_catch, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> Z =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N_years, N_sites,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> X =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N_years, N_sites,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> Pc_mat =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N_years, N_sites,
          DUMMY_VAR__);
      current_statement__ = 15;
      stan::model::assign(Pc, stan::math::inv_logit(Pc_logit),
        "assigning variable Pc");
      current_statement__ = 16;
      stan::model::assign(Pc_mat,
        stan::math::rep_matrix(0.0, N_years, N_sites),
        "assigning variable Pc_mat");
      current_statement__ = 19;
      for (int k = 1; k <= N_catch; ++k) {
        current_statement__ = 17;
        stan::model::assign(Pc_mat,
          stan::model::rvalue(Pc, "Pc", stan::model::index_uni(k)),
          "assigning variable Pc_mat",
          stan::model::index_uni(
            stan::model::rvalue(catch_row, "catch_row",
              stan::model::index_uni(k))),
          stan::model::index_uni(
            stan::model::rvalue(catch_col, "catch_col",
              stan::model::index_uni(k))));
      }
      current_statement__ = 23;
      for (int j = 1; j <= N_sites; ++j) {
        current_statement__ = 20;
        stan::model::assign(Z,
          stan::model::rvalue(Z_init, "Z_init", stan::model::index_uni(j)),
          "assigning variable Z", stan::model::index_uni(1),
          stan::model::index_uni(j));
        current_statement__ = 21;
        stan::model::assign(X,
          (stan::model::rvalue(Z, "Z", stan::model::index_uni(1),
             stan::model::index_uni(j)) +
          stan::math::log1m(
            stan::model::rvalue(Pc_mat, "Pc_mat", stan::model::index_uni(1),
              stan::model::index_uni(j)))), "assigning variable X",
          stan::model::index_uni(1), stan::model::index_uni(j));
      }
      current_statement__ = 29;
      for (int t = 2; t <= N_years; ++t) {
        current_statement__ = 27;
        for (int j = 1; j <= N_sites; ++j) {
          current_statement__ = 24;
          stan::model::assign(Z,
            (((stan::model::rvalue(X, "X", stan::model::index_uni((t - 1)),
                 stan::model::index_uni(j)) + U) + (pdocoef *
            stan::model::rvalue(pdo, "pdo", stan::model::index_uni((t - 1)))))
            + (sigma *
            stan::model::rvalue(delta_raw, "delta_raw",
              stan::model::index_uni((t - 1)), stan::model::index_uni(j)))),
            "assigning variable Z", stan::model::index_uni(t),
            stan::model::index_uni(j));
          current_statement__ = 25;
          stan::model::assign(X,
            (stan::model::rvalue(Z, "Z", stan::model::index_uni(t),
               stan::model::index_uni(j)) +
            stan::math::log1m(
              stan::model::rvalue(Pc_mat, "Pc_mat",
                stan::model::index_uni(t), stan::model::index_uni(j)))),
            "assigning variable X", stan::model::index_uni(t),
            stan::model::index_uni(j));
        }
      }
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "Pc", Pc, 0);
      current_statement__ = 9;
      stan::math::check_less_or_equal(function__, "Pc", Pc, 1);
      {
        current_statement__ = 44;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(U,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 45;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(pdocoef,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 46;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(sigma,
                         static_cast<double>(3), static_cast<double>(0), 2.5));
        current_statement__ = 47;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(sigma_obs,
                         static_cast<double>(3), static_cast<double>(0), 2.5));
        current_statement__ = 48;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_q,
                         static_cast<double>(0), static_cast<double>(2)));
        current_statement__ = 49;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(Pc_logit, -(1.386),
                         0.707));
        current_statement__ = 50;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(Z_init,
                         static_cast<double>(5), static_cast<double>(10)));
        current_statement__ = 51;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                         stan::math::to_vector(delta_raw)));
        current_statement__ = 63;
        if (stan::math::logical_eq(prior_only, 0)) {
          current_statement__ = 58;
          for (int t = 1; t <= N_years; ++t) {
            current_statement__ = 56;
            for (int j = 1; j <= N_sites; ++j) {
              current_statement__ = 54;
              if (stan::math::logical_eq(
                    stan::model::rvalue(Y_obs, "Y_obs",
                      stan::model::index_uni(t), stan::model::index_uni(j)),
                    1)) {
                current_statement__ = 52;
                lp_accum__.add(stan::math::normal_lpdf<propto__>(
                                 stan::model::rvalue(Y, "Y",
                                   stan::model::index_uni(t),
                                   stan::model::index_uni(j)),
                                 (stan::model::rvalue(X, "X",
                                    stan::model::index_uni(t),
                                    stan::model::index_uni(j)) +
                                 stan::model::rvalue(log_q, "log_q",
                                   stan::model::index_uni(
                                     stan::model::rvalue(q_idx, "q_idx",
                                       stan::model::index_uni(t))))),
                                 sigma_obs));
              }
            }
          }
          current_statement__ = 61;
          for (int k = 1; k <= N_catch; ++k) {
            current_statement__ = 59;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(
                             stan::model::rvalue(log_catch, "log_catch",
                               stan::model::index_uni(k)),
                             (stan::model::rvalue(Z, "Z",
                                stan::model::index_uni(
                                  stan::model::rvalue(catch_row, "catch_row",
                                    stan::model::index_uni(k))),
                                stan::model::index_uni(
                                  stan::model::rvalue(catch_col, "catch_col",
                                    stan::model::index_uni(k)))) +
                             stan::math::log_inv_logit(
                               stan::model::rvalue(Pc_logit, "Pc_logit",
                                 stan::model::index_uni(k)))), sigma_catch));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "herring_metapop_v1_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto U = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto pdocoef = in__.template read<local_scalar_t__>();
      current_statement__ = 3;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 4;
      auto sigma_obs =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 5;
      auto log_q =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(2);
      current_statement__ = 6;
      auto Pc_logit =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_catch);
      current_statement__ = 7;
      auto delta_raw =
        in__.template read<
          Eigen::Matrix<local_scalar_t__,-1,-1>>(delta_raw_1dim__, N_sites);
      current_statement__ = 8;
      auto Z_init =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_sites);
      Eigen::Matrix<local_scalar_t__,-1,1> Pc =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_catch, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> Z =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N_years, N_sites,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> X =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N_years, N_sites,
          DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> Pc_mat =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N_years, N_sites,
          DUMMY_VAR__);
      current_statement__ = 15;
      stan::model::assign(Pc, stan::math::inv_logit(Pc_logit),
        "assigning variable Pc");
      current_statement__ = 16;
      stan::model::assign(Pc_mat,
        stan::math::rep_matrix(0.0, N_years, N_sites),
        "assigning variable Pc_mat");
      current_statement__ = 19;
      for (int k = 1; k <= N_catch; ++k) {
        current_statement__ = 17;
        stan::model::assign(Pc_mat,
          stan::model::rvalue(Pc, "Pc", stan::model::index_uni(k)),
          "assigning variable Pc_mat",
          stan::model::index_uni(
            stan::model::rvalue(catch_row, "catch_row",
              stan::model::index_uni(k))),
          stan::model::index_uni(
            stan::model::rvalue(catch_col, "catch_col",
              stan::model::index_uni(k))));
      }
      current_statement__ = 23;
      for (int j = 1; j <= N_sites; ++j) {
        current_statement__ = 20;
        stan::model::assign(Z,
          stan::model::rvalue(Z_init, "Z_init", stan::model::index_uni(j)),
          "assigning variable Z", stan::model::index_uni(1),
          stan::model::index_uni(j));
        current_statement__ = 21;
        stan::model::assign(X,
          (stan::model::rvalue(Z, "Z", stan::model::index_uni(1),
             stan::model::index_uni(j)) +
          stan::math::log1m(
            stan::model::rvalue(Pc_mat, "Pc_mat", stan::model::index_uni(1),
              stan::model::index_uni(j)))), "assigning variable X",
          stan::model::index_uni(1), stan::model::index_uni(j));
      }
      current_statement__ = 29;
      for (int t = 2; t <= N_years; ++t) {
        current_statement__ = 27;
        for (int j = 1; j <= N_sites; ++j) {
          current_statement__ = 24;
          stan::model::assign(Z,
            (((stan::model::rvalue(X, "X", stan::model::index_uni((t - 1)),
                 stan::model::index_uni(j)) + U) + (pdocoef *
            stan::model::rvalue(pdo, "pdo", stan::model::index_uni((t - 1)))))
            + (sigma *
            stan::model::rvalue(delta_raw, "delta_raw",
              stan::model::index_uni((t - 1)), stan::model::index_uni(j)))),
            "assigning variable Z", stan::model::index_uni(t),
            stan::model::index_uni(j));
          current_statement__ = 25;
          stan::model::assign(X,
            (stan::model::rvalue(Z, "Z", stan::model::index_uni(t),
               stan::model::index_uni(j)) +
            stan::math::log1m(
              stan::model::rvalue(Pc_mat, "Pc_mat",
                stan::model::index_uni(t), stan::model::index_uni(j)))),
            "assigning variable X", stan::model::index_uni(t),
            stan::model::index_uni(j));
        }
      }
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "Pc", Pc, 0);
      current_statement__ = 9;
      stan::math::check_less_or_equal(function__, "Pc", Pc, 1);
      {
        current_statement__ = 44;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(U,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 45;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(pdocoef,
                         static_cast<double>(0), static_cast<double>(1)));
        current_statement__ = 46;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(sigma,
                         static_cast<double>(3), static_cast<double>(0), 2.5));
        current_statement__ = 47;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(sigma_obs,
                         static_cast<double>(3), static_cast<double>(0), 2.5));
        current_statement__ = 48;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_q,
                         static_cast<double>(0), static_cast<double>(2)));
        current_statement__ = 49;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(Pc_logit, -(1.386),
                         0.707));
        current_statement__ = 50;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(Z_init,
                         static_cast<double>(5), static_cast<double>(10)));
        current_statement__ = 51;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                         stan::math::to_vector(delta_raw)));
        current_statement__ = 63;
        if (stan::math::logical_eq(prior_only, 0)) {
          current_statement__ = 58;
          for (int t = 1; t <= N_years; ++t) {
            current_statement__ = 56;
            for (int j = 1; j <= N_sites; ++j) {
              current_statement__ = 54;
              if (stan::math::logical_eq(
                    stan::model::rvalue(Y_obs, "Y_obs",
                      stan::model::index_uni(t), stan::model::index_uni(j)),
                    1)) {
                current_statement__ = 52;
                lp_accum__.add(stan::math::normal_lpdf<propto__>(
                                 stan::model::rvalue(Y, "Y",
                                   stan::model::index_uni(t),
                                   stan::model::index_uni(j)),
                                 (stan::model::rvalue(X, "X",
                                    stan::model::index_uni(t),
                                    stan::model::index_uni(j)) +
                                 stan::model::rvalue(log_q, "log_q",
                                   stan::model::index_uni(
                                     stan::model::rvalue(q_idx, "q_idx",
                                       stan::model::index_uni(t))))),
                                 sigma_obs));
              }
            }
          }
          current_statement__ = 61;
          for (int k = 1; k <= N_catch; ++k) {
            current_statement__ = 59;
            lp_accum__.add(stan::math::normal_lpdf<propto__>(
                             stan::model::rvalue(log_catch, "log_catch",
                               stan::model::index_uni(k)),
                             (stan::model::rvalue(Z, "Z",
                                stan::model::index_uni(
                                  stan::model::rvalue(catch_row, "catch_row",
                                    stan::model::index_uni(k))),
                                stan::model::index_uni(
                                  stan::model::rvalue(catch_col, "catch_col",
                                    stan::model::index_uni(k)))) +
                             stan::math::log_inv_logit(
                               stan::model::rvalue(Pc_logit, "Pc_logit",
                                 stan::model::index_uni(k)))), sigma_catch));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "herring_metapop_v1_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto U = in__.template read<local_scalar_t__>();
      current_statement__ = 2;
      auto pdocoef = in__.template read<local_scalar_t__>();
      current_statement__ = 3;
      auto sigma =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 4;
      auto sigma_obs =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 5;
      auto log_q =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(2);
      current_statement__ = 6;
      auto Pc_logit =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_catch);
      current_statement__ = 7;
      auto delta_raw =
        in__.template read<
          Eigen::Matrix<local_scalar_t__,-1,-1>>(delta_raw_1dim__, N_sites);
      current_statement__ = 8;
      auto Z_init =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_sites);
      Eigen::Matrix<double,-1,1> Pc =
        Eigen::Matrix<double,-1,1>::Constant(N_catch,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> Z =
        Eigen::Matrix<double,-1,-1>::Constant(N_years, N_sites,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> X =
        Eigen::Matrix<double,-1,-1>::Constant(N_years, N_sites,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> Pc_mat =
        Eigen::Matrix<double,-1,-1>::Constant(N_years, N_sites,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(U);
      out__.write(pdocoef);
      out__.write(sigma);
      out__.write(sigma_obs);
      out__.write(log_q);
      out__.write(Pc_logit);
      out__.write(delta_raw);
      out__.write(Z_init);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 15;
      stan::model::assign(Pc, stan::math::inv_logit(Pc_logit),
        "assigning variable Pc");
      current_statement__ = 16;
      stan::model::assign(Pc_mat,
        stan::math::rep_matrix(0.0, N_years, N_sites),
        "assigning variable Pc_mat");
      current_statement__ = 19;
      for (int k = 1; k <= N_catch; ++k) {
        current_statement__ = 17;
        stan::model::assign(Pc_mat,
          stan::model::rvalue(Pc, "Pc", stan::model::index_uni(k)),
          "assigning variable Pc_mat",
          stan::model::index_uni(
            stan::model::rvalue(catch_row, "catch_row",
              stan::model::index_uni(k))),
          stan::model::index_uni(
            stan::model::rvalue(catch_col, "catch_col",
              stan::model::index_uni(k))));
      }
      current_statement__ = 23;
      for (int j = 1; j <= N_sites; ++j) {
        current_statement__ = 20;
        stan::model::assign(Z,
          stan::model::rvalue(Z_init, "Z_init", stan::model::index_uni(j)),
          "assigning variable Z", stan::model::index_uni(1),
          stan::model::index_uni(j));
        current_statement__ = 21;
        stan::model::assign(X,
          (stan::model::rvalue(Z, "Z", stan::model::index_uni(1),
             stan::model::index_uni(j)) +
          stan::math::log1m(
            stan::model::rvalue(Pc_mat, "Pc_mat", stan::model::index_uni(1),
              stan::model::index_uni(j)))), "assigning variable X",
          stan::model::index_uni(1), stan::model::index_uni(j));
      }
      current_statement__ = 29;
      for (int t = 2; t <= N_years; ++t) {
        current_statement__ = 27;
        for (int j = 1; j <= N_sites; ++j) {
          current_statement__ = 24;
          stan::model::assign(Z,
            (((stan::model::rvalue(X, "X", stan::model::index_uni((t - 1)),
                 stan::model::index_uni(j)) + U) + (pdocoef *
            stan::model::rvalue(pdo, "pdo", stan::model::index_uni((t - 1)))))
            + (sigma *
            stan::model::rvalue(delta_raw, "delta_raw",
              stan::model::index_uni((t - 1)), stan::model::index_uni(j)))),
            "assigning variable Z", stan::model::index_uni(t),
            stan::model::index_uni(j));
          current_statement__ = 25;
          stan::model::assign(X,
            (stan::model::rvalue(Z, "Z", stan::model::index_uni(t),
               stan::model::index_uni(j)) +
            stan::math::log1m(
              stan::model::rvalue(Pc_mat, "Pc_mat",
                stan::model::index_uni(t), stan::model::index_uni(j)))),
            "assigning variable X", stan::model::index_uni(t),
            stan::model::index_uni(j));
        }
      }
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "Pc", Pc, 0);
      current_statement__ = 9;
      stan::math::check_less_or_equal(function__, "Pc", Pc, 1);
      if (emit_transformed_parameters__) {
        out__.write(Pc);
        out__.write(Z);
        out__.write(X);
        out__.write(Pc_mat);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(log_lik_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> Y_rep =
        Eigen::Matrix<double,-1,-1>::Constant(N_years, N_sites,
          std::numeric_limits<double>::quiet_NaN());
      {
        int idx = std::numeric_limits<int>::min();
        current_statement__ = 30;
        idx = 0;
        current_statement__ = 42;
        for (int t = 1; t <= N_years; ++t) {
          current_statement__ = 40;
          for (int j = 1; j <= N_sites; ++j) {
            current_statement__ = 31;
            idx = (idx + 1);
            current_statement__ = 38;
            if (stan::math::logical_eq(
                  stan::model::rvalue(Y_obs, "Y_obs",
                    stan::model::index_uni(t), stan::model::index_uni(j)), 1)) {
              current_statement__ = 35;
              stan::model::assign(log_lik,
                stan::math::normal_lpdf<false>(
                  stan::model::rvalue(Y, "Y", stan::model::index_uni(t),
                    stan::model::index_uni(j)),
                  (stan::model::rvalue(X, "X", stan::model::index_uni(t),
                     stan::model::index_uni(j)) +
                  stan::model::rvalue(log_q, "log_q",
                    stan::model::index_uni(
                      stan::model::rvalue(q_idx, "q_idx",
                        stan::model::index_uni(t))))), sigma_obs),
                "assigning variable log_lik", stan::model::index_uni(idx));
              current_statement__ = 36;
              stan::model::assign(Y_rep,
                stan::math::normal_rng(
                  (stan::model::rvalue(X, "X", stan::model::index_uni(t),
                     stan::model::index_uni(j)) +
                  stan::model::rvalue(log_q, "log_q",
                    stan::model::index_uni(
                      stan::model::rvalue(q_idx, "q_idx",
                        stan::model::index_uni(t))))), sigma_obs, base_rng__),
                "assigning variable Y_rep", stan::model::index_uni(t),
                stan::model::index_uni(j));
            } else {
              current_statement__ = 32;
              stan::model::assign(log_lik, 0.0, "assigning variable log_lik",
                stan::model::index_uni(idx));
              current_statement__ = 33;
              stan::model::assign(Y_rep, 0.0, "assigning variable Y_rep",
                stan::model::index_uni(t), stan::model::index_uni(j));
            }
          }
        }
      }
      out__.write(log_lik);
      out__.write(Y_rep);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ U = DUMMY_VAR__;
      current_statement__ = 1;
      U = in__.read<local_scalar_t__>();
      out__.write(U);
      local_scalar_t__ pdocoef = DUMMY_VAR__;
      current_statement__ = 2;
      pdocoef = in__.read<local_scalar_t__>();
      out__.write(pdocoef);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 3;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
      local_scalar_t__ sigma_obs = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_obs = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_obs);
      Eigen::Matrix<local_scalar_t__,-1,1> log_q =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(log_q,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(2),
        "assigning variable log_q");
      out__.write(log_q);
      Eigen::Matrix<local_scalar_t__,-1,1> Pc_logit =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_catch, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(Pc_logit,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_catch),
        "assigning variable Pc_logit");
      out__.write(Pc_logit);
      Eigen::Matrix<local_scalar_t__,-1,-1> delta_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(delta_raw_1dim__,
          N_sites, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(delta_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(delta_raw_1dim__,
          N_sites), "assigning variable delta_raw");
      out__.write(delta_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> Z_init =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_sites, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(Z_init,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_sites),
        "assigning variable Z_init");
      out__.write(Z_init);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "U", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "pdocoef",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sigma_obs",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "log_q", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "Pc_logit",
        "double", std::vector<size_t>{static_cast<size_t>(N_catch)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "delta_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(delta_raw_1dim__),
          static_cast<size_t>(N_sites)});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "Z_init", "double",
        std::vector<size_t>{static_cast<size_t>(N_sites)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ U = DUMMY_VAR__;
      current_statement__ = 1;
      U = context__.vals_r("U")[(1 - 1)];
      out__.write(U);
      local_scalar_t__ pdocoef = DUMMY_VAR__;
      current_statement__ = 2;
      pdocoef = context__.vals_r("pdocoef")[(1 - 1)];
      out__.write(pdocoef);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 3;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
      local_scalar_t__ sigma_obs = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_obs = context__.vals_r("sigma_obs")[(1 - 1)];
      out__.write_free_lb(0, sigma_obs);
      Eigen::Matrix<local_scalar_t__,-1,1> log_q =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> log_q_flat__;
        current_statement__ = 5;
        log_q_flat__ = context__.vals_r("log_q");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          stan::model::assign(log_q, log_q_flat__[(pos__ - 1)],
            "assigning variable log_q", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(log_q);
      Eigen::Matrix<local_scalar_t__,-1,1> Pc_logit =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_catch, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> Pc_logit_flat__;
        current_statement__ = 6;
        Pc_logit_flat__ = context__.vals_r("Pc_logit");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_catch; ++sym1__) {
          stan::model::assign(Pc_logit, Pc_logit_flat__[(pos__ - 1)],
            "assigning variable Pc_logit", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(Pc_logit);
      Eigen::Matrix<local_scalar_t__,-1,-1> delta_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(delta_raw_1dim__,
          N_sites, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> delta_raw_flat__;
        current_statement__ = 7;
        delta_raw_flat__ = context__.vals_r("delta_raw");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= delta_raw_1dim__; ++sym2__) {
            stan::model::assign(delta_raw, delta_raw_flat__[(pos__ - 1)],
              "assigning variable delta_raw", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(delta_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> Z_init =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_sites, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> Z_init_flat__;
        current_statement__ = 8;
        Z_init_flat__ = context__.vals_r("Z_init");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
          stan::model::assign(Z_init, Z_init_flat__[(pos__ - 1)],
            "assigning variable Z_init", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(Z_init);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"U", "pdocoef", "sigma", "sigma_obs",
                "log_q", "Pc_logit", "delta_raw", "Z_init"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"Pc", "Z", "X", "Pc_mat"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik", "Y_rep"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(2)},
                std::vector<size_t>{static_cast<size_t>(N_catch)},
                std::vector<size_t>{static_cast<size_t>(delta_raw_1dim__),
                  static_cast<size_t>(N_sites)},
                std::vector<size_t>{static_cast<size_t>(N_sites)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N_catch)},
             std::vector<size_t>{static_cast<size_t>(N_years),
               static_cast<size_t>(N_sites)},
             std::vector<size_t>{static_cast<size_t>(N_years),
               static_cast<size_t>(N_sites)},
             std::vector<size_t>{static_cast<size_t>(N_years),
               static_cast<size_t>(N_sites)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(log_lik_1dim__)},
             std::vector<size_t>{static_cast<size_t>(N_years),
               static_cast<size_t>(N_sites)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "U");
    param_names__.emplace_back(std::string() + "pdocoef");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "sigma_obs");
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      param_names__.emplace_back(std::string() + "log_q" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_catch; ++sym1__) {
      param_names__.emplace_back(std::string() + "Pc_logit" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= delta_raw_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "delta_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
      param_names__.emplace_back(std::string() + "Z_init" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N_catch; ++sym1__) {
        param_names__.emplace_back(std::string() + "Pc" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_years; ++sym2__) {
          param_names__.emplace_back(std::string() + "Z" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_years; ++sym2__) {
          param_names__.emplace_back(std::string() + "X" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_years; ++sym2__) {
          param_names__.emplace_back(std::string() + "Pc_mat" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= log_lik_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_years; ++sym2__) {
          param_names__.emplace_back(std::string() + "Y_rep" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "U");
    param_names__.emplace_back(std::string() + "pdocoef");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "sigma_obs");
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      param_names__.emplace_back(std::string() + "log_q" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_catch; ++sym1__) {
      param_names__.emplace_back(std::string() + "Pc_logit" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= delta_raw_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "delta_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
      param_names__.emplace_back(std::string() + "Z_init" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N_catch; ++sym1__) {
        param_names__.emplace_back(std::string() + "Pc" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_years; ++sym2__) {
          param_names__.emplace_back(std::string() + "Z" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_years; ++sym2__) {
          param_names__.emplace_back(std::string() + "X" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_years; ++sym2__) {
          param_names__.emplace_back(std::string() + "Pc_mat" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= log_lik_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N_sites; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_years; ++sym2__) {
          param_names__.emplace_back(std::string() + "Y_rep" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"U\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"pdocoef\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_obs\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_q\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"Pc_logit\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_catch) + "},\"block\":\"parameters\"},{\"name\":\"delta_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(delta_raw_1dim__) + ",\"cols\":" + std::to_string(N_sites) + "},\"block\":\"parameters\"},{\"name\":\"Z_init\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_sites) + "},\"block\":\"parameters\"},{\"name\":\"Pc\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_catch) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Z\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_years) + ",\"cols\":" + std::to_string(N_sites) + "},\"block\":\"transformed_parameters\"},{\"name\":\"X\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_years) + ",\"cols\":" + std::to_string(N_sites) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Pc_mat\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_years) + ",\"cols\":" + std::to_string(N_sites) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_lik_1dim__) + "},\"block\":\"generated_quantities\"},{\"name\":\"Y_rep\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_years) + ",\"cols\":" + std::to_string(N_sites) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"U\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"pdocoef\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_obs\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_q\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"Pc_logit\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_catch) + "},\"block\":\"parameters\"},{\"name\":\"delta_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(delta_raw_1dim__) + ",\"cols\":" + std::to_string(N_sites) + "},\"block\":\"parameters\"},{\"name\":\"Z_init\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_sites) + "},\"block\":\"parameters\"},{\"name\":\"Pc\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_catch) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Z\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_years) + ",\"cols\":" + std::to_string(N_sites) + "},\"block\":\"transformed_parameters\"},{\"name\":\"X\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_years) + ",\"cols\":" + std::to_string(N_sites) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Pc_mat\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_years) + ",\"cols\":" + std::to_string(N_sites) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_lik_1dim__) + "},\"block\":\"generated_quantities\"},{\"name\":\"Y_rep\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N_years) + ",\"cols\":" + std::to_string(N_sites) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1 + 1 + 1 + 2 + N_catch +
      (delta_raw_1dim__ * N_sites) + N_sites;
    const size_t num_transformed = emit_transformed_parameters * (N_catch +
      (N_years * N_sites) + (N_years * N_sites) + (N_years * N_sites));
    const size_t num_gen_quantities = emit_generated_quantities *
      (log_lik_1dim__ + (N_years * N_sites));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1 + 1 + 1 + 1 + 2 + N_catch +
      (delta_raw_1dim__ * N_sites) + N_sites;
    const size_t num_transformed = emit_transformed_parameters * (N_catch +
      (N_years * N_sites) + (N_years * N_sites) + (N_years * N_sites));
    const size_t num_gen_quantities = emit_generated_quantities *
      (log_lik_1dim__ + (N_years * N_sites));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = herring_metapop_v1_model_namespace::herring_metapop_v1_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return herring_metapop_v1_model_namespace::profiles__;
}
#endif